### ISSUE TITLE
[bug] sing-box on Linux

### ISSUE THREAD

**Issue by zhanghengxin** [senzyo/blog#2]
|Field|Value|
|-|-|
|Title|sing-box on Linux|
|Url|https://senzyo.net/2024-2/|
|Filename|https://github.com/senzyo/blog/blob/master/content/posts/2024-2/index.md|

url_gene="https://example.com"  # 生成配置的后端地址

这个是干什么用的？如果没有怎么办？

**Comment by senzyo** [comment]
@zhanghengxin 指“将机场提供的配置转换为适用于 sing-box 的配置”的服务，你可以阅读博客中，同系列的上一篇文章: https://senzyo.net/2024-1/
